config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :home, only:[:index]
  resources :registry, only:[:index, :create, :edit, :update, :show, :destroy] do
    collection do
      post 'search'
      get 'sort'
    end
    member do
      post 'publish'
      post 'unpublish'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category

	scope :published, -> { where(publish_status: true) }
	scope :with_category, -> { includes(:category).order("created_at DESC") }
	
	validates :book_name, :presence => {:message => "Book name can't be blank." }
	validates :book_description, :presence => {:message => "Book Description can't be blank." }
	validates :author_name, :presence => {:message => "Author name can't be blank." }
	validates :price, :presence => {:message => "Price can't be blank." }
	validates :book_isbn, 
      :presence => {:message => "ISBN can't be blank." },
      :uniqueness => {:message => "ISBN already exists."},
      :length => { :maximum => 100, :message => "Invalid ISBN"}
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@books = Book.published
  end

end

app/controllers/registry_controller.rb
class RegistryController < ApplicationController
  
  def index
    @books = Book.with_category
    @categories = Category.all
    @new_book = Book.new
  end

  def create
    book = Book.new(book_params)
    if book.save
      redirect_to registry_index_path
    end
  end

  def show
    @book_info = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to registry_index_path
    end
  end

  def destroy
  	@book = Book.find(params[:id])
    if @book.destroy
      redirect_to registry_index_path
    end
  end

  def publish
    @book = Book.find(params[:id])
    if @book.update(publish_status: true)
      redirect_to registry_index_path
    end
  end

  def unpublish
    @book = Book.find(params[:id])
    if @book.update(publish_status: false)
      redirect_to registry_index_path
    end
  end

  def search
    @books = Book.where(search_query)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def sort
    case params[:selected_value]
    when "book_name_asc"
      @books = Book.order("book_name ASC")
    when "book_name_desc"
      @books = Book.order("book_name DESC")
    when "author_name_asc"
      @books = Book.order("author_name ASC")
    when "author_name_desc"
      @books = Book.order("author_name DESC")
    when "price_low_high"
      @books = Book.order("price ASC")
    when "price_high_low"
      @books = Book.order("price DESC")
    end
  end
end

private

  def book_params
    params.require(:book).permit(:book_name, :book_description, :author_name, :book_isbn, :price, :publish_status, :category_id)
  end

  def search_query
    book_name = params[:search][:book_name]
    author_name = params[:search][:author_name]
    book_isbn = params[:search][:book_isbn]
    search_query = ""
    search_query += "book_name ILIKE '%"+book_name+"%'" if book_name.present?
    if book_name.present? && author_name.present?
      search_query += "AND author_name ILIKE '%"+author_name+"%'"
    elsif author_name.present?
      search_query += "author_name ILIKE '%"+author_name+"%'"
    end
    if (book_name.present? || author_name.present?) && book_isbn.present?
      search_query += "AND book_isbn ILIKE '"+book_isbn+"'"
    elsif book_isbn.present?
      search_query += "book_isbn ILIKE '"+book_isbn+"'"
    end
    search_query
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registry_helper.rb
module RegistryHelper
  def isPublished(publish_status, book_id)
  	return publish_status ? "<a href='/registry/#{book_id}/unpublish' class='btn btn-outline-warning' data-method='post'>Unpublish</a>".html_safe : "<a href='/registry/#{book_id}/publish' class='btn btn-success' data-method='post'>Publish</a>".html_safe
  end
end

app/views/home/index.html.erb
<div class="box">
	<div class="container">
		<h2>Published Books</h2>
		<hr>
		<div class="row">
			<% @books.each do |book| %>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<div class="box-part text-center">
						<i class="custom-fa fa fa-book fa-4x" aria-hidden="true"></i>
							<div class="title">
								<h3><%= truncate(book.book_name, :length => 25, :separator => ' ') %></h3>
							</div>
						<div class="text">
							<span>
								<%= truncate(book.book_description, :length => 35, :separator => ' ')%>		
							</span>
						</div>
						<%= link_to "View Details" ,registry_path(id: book.id), class:"btn btn-secondary", method: "GET"%> 
					</div>
				</div>
			<% end %>
		</div>		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookRegistry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="container">
      <%= render "layouts/shared/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <%= link_to root_path , class:"navbar-brand" do %>
    Book-Registry App
    <i class="fa fa-book" aria-hidden="true"></i>
  <% end %>
  <%= link_to root_path , class:"navbar-brand btn btn-warning" do %>
    <i class="fa fa-home" aria-hidden="true"></i>
  <% end %>
  <%= link_to registry_index_path , class:"navbar-brand btn btn-warning" do %>
    Manage Registry
    <i class="fa fa-tachometer" aria-hidden="true"></i>
  <% end %>
</nav>

app/views/registry/_book_list.html.erb
<table class="table">
	<thead class="thead-dark">
		<tr>
			<th scope="col">Title</th>
			<th scope="col">Author</th>
			<th scope="col">Category</th>
			<th scope="col">Price</th>
			<th scope="col">Status</th>
			<th scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
			<tr>
				<td><%= book.book_name%></td>
				<td><%= book.author_name%></td>
				<td><%= book.category.name%></td>
				<td><%= book.price%></td>
				<td><%= isPublished(book.publish_status, book.id)%></td>
				<td class="action-links">
				<%= link_to registry_path(id:book.id), title:"View details" do %>
				  <i class="fa fa-eye" aria-hidden="true"></i>
				<% end %>
				 &nbsp;&nbsp;
				<%= link_to edit_registry_path(id:book.id), title:"Edit details" do %>
				  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 
				<% end %>
				 &nbsp;&nbsp;
				<%= link_to registry_path(id:book.id), method: "DELETE", title:"Delete" do %>
				  <i class="fa fa-trash" aria-hidden="true"></i>
				<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/registry/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
		<div>
			<%= form_for(@book, url: registry_path,  method: :put, html: { id: "", autocomplete: "off"}) do |f| %>
				<div class="form-group row">
				<label class="col-sm-2 col-form-label">Category</label>
				<div class="col-sm-10"> 
				<select id="inputState" class="form-control" name="book[category_id]">
				<% @categories.each do |category| %>
					<% if category.id == @book.category_id %>
					  <option value="<%= category.id%>" selected> <%= category.name %> </option>
					<% else %>
					  <option value="<%= category.id%>"> <%= category.name %> </option>
					<% end %>
				<% end %>
				</select>
				</div>
				</div>
				<div class="form-group row">
				<label class="col-sm-2 col-form-label">Title</label>
				<div class="col-sm-10"> 
				  <%= f.text_field :book_name  , class:"form-control", :required => true%>
				</div>
				</div>
				<div class="form-group row">
				<label class="col-sm-2 col-form-label">Description</label>
				<div class="col-sm-10"> 
				  <%= f.text_area :book_description  , class:"form-control", :required => true%>
				</div>
				</div>
				<div class="form-group row">
				<label class="col-sm-2 col-form-label">Author</label>
				<div class="col-sm-10"> 
				  <%= f.text_field :author_name  , class:"form-control", :required => true%>
				</div>
				</div>
				<div class="form-group row">
				<label class="col-sm-2 col-form-label">ISBN</label>
				<div class="col-sm-10"> 
				  <%= f.text_field :book_isbn  , class:"form-control", :required => true%>
				</div>
				</div>
				<div class="form-group row">
				<label class="col-sm-2 col-form-label">Price</label>
				<div class="col-sm-10"> 
				  <%= f.text_field :price  , class:"form-control", :required => true%>
				</div>
				</div>
				<div class="form-group row">
				<div>
				<a href="javascript:history.back()" class="btn btn-secondary">Go Back</a>
				<button type="submit" class="btn btn-warning">Update</button>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/registry/forms/_new.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add New Book</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(@new_book, url: registry_index_path,  method: :post, html: { id: "", autocomplete: "off"}) do |f| %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Category*</label>
            <div class="col-sm-10"> 
              <select id="inputState" class="form-control" name="book[category_id]">
              <% @categories.each do |category| %>
                <option value="<%= category.id%>"> <%= category.name %> </option>
              <% end %>
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Title*</label>
            <div class="col-sm-10"> 
              <%= f.text_field :book_name  , class:"form-control", :required => true%>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Description*</label>
            <div class="col-sm-10"> 
              <%= f.text_area :book_description  , class:"form-control", :required => true%>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Author*</label>
            <div class="col-sm-10"> 
              <%= f.text_field :author_name  , class:"form-control", :required => true%>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">ISBN*</label>
            <div class="col-sm-10"> 
              <%= f.text_field :book_isbn  , class:"form-control", :required => true, :minlength => 10, :maxlength => 13%>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Price*</label>
            <div class="col-sm-10"> 
              <%= f.text_field :price  , class:"form-control", :required => true%>
            </div>
          </div>
          <input type="hidden" name="book[publish_status]" value="false">
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Create</button>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/registry/forms/_search.html.erb
<div class="search_box">
  <h4>Search Book Registry</h4>
  <%= form_for(:search, url: search_registry_index_path, remote: true,  method: :post, html: { id: "", autocomplete: "off"}) do |f| %>
    <%= f.text_field :book_name, placeholder:"Book name..." %>
    <%= f.text_field :author_name, placeholder:"Author name..." %>
    <%= f.text_field :book_isbn, placeholder:"ISBN..." %>
    <%= f.submit  value:"Search", class:"btn btn-info"%>
  <% end %>
</div>

app/views/registry/forms/_sort.html.erb
<div class="search_box">
  <h6>Sort by
	  <select id="sort_by">
	  	<option value="0">choose..</option>
	  	<option value="book_name_asc">Book Name A-Z</option>
	  	<option value="book_name_desc">Book Name Z-A</option>
	  	<option value="author_name_asc">Author Name A-Z</option>
	  	<option value="author_name_desc">Author Name Z-A</option>
	  	<option value="price_low_high">Price Low - High</option>
	  	<option value="price_high_low">Price High - Low</option>
	  </select>
  </h6>
</div>

app/views/registry/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div id="id1"></div>
			<h2>Book List</h2>
			<div class="margin-top-bottom-btn  col-md-12">
			  
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
			<i class="fa fa-plus-circle" aria-hidden="true"></i>
			&nbsp;
			Add New Book
			</button><br><br>
			<%= render "registry/forms/search"%>
			  <%= render "registry/forms/sort"%>
			</div>
			<div id="book_list">
			  <%= render "registry/book_list"%>
			</div>
		</div>
	</div>
</div>
<%= render 'registry/forms/new' %>

app/views/registry/search.js.erb
$("#book_list").html("<%= j render 'registry/book_list'%>")

app/views/registry/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div>
				<h2><%= @book_info.book_name %></h2>
				<p><b>Author:</b> <br><%= @book_info.author_name %></p>
				<p><b>Description:</b> <br><%= @book_info.book_description %></p>
				<p><b>ISBN:</b> <br><%= @book_info.book_isbn %></p>
				<p><b>Price:</b> <br><%= @book_info.price %></p>
				<a href="javascript:history.back()" class="btn btn-secondary">Go Back</a>
			</div>
		</div>
	</div>
</div>

app/views/registry/sort.js.erb
$("#book_list").html("<%= j render 'registry/book_list'%>");